services:
  database:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

  data_loader:
    build: ./data_loader
    depends_on:
      - database

  summary_output:
    build: ./summary_output
    depends_on:
      - database
    volumes:
      - ./output:/app/output